# Generated by Django 5.2 on 2026-04-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mahasisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=12, unique=True)),
                ('nama', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profile', models.ImageField(blank=True, default='profile/default.jpg', null=True, upload_to='profile/')),
                ('nomor', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
