# Generated by Django 5.2 on 2026-04-01 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mahasisa',
            new_name='mahasiswa',
        ),
    ]
