# Generated by Django 5.2 on 2026-04-01 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_mahasisa_mahasiswa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahasiswa',
            name='password',
        ),
    ]
